### ISSUE TITLE
Rails 4.2 Active Job Adapter

### ISSUE THREAD

**Issue by bitboxer** [beanstalkd/beaneater#46]
Is anyone here already working on the [ActiveJob](http://weblog.rubyonrails.org/2014/8/20/Rails-4-2-beta1/) adapter for Rails 4.2?

Looks not that hard to implemnt after looking at one of the [other implementations](https://github.com/rails/rails/blob/6d92dcc7bd25f1533d3fc282dd4909ac8ed1a2dc/activejob/lib/active_job/queue_adapters/resque_adapter.rb).

**Comment by alup** [comment]
Closing this as it has been handled by backburner implementation.
@bitboxer feel free to propose a new solution if you want to interact directly with the lower level client.
