### ISSUE TITLE
Beaneater.new requires one argument

### ISSUE THREAD

**Issue by kuon** [beanstalkd/beaneater#60]
```ruby
client = Beaneater.new
```

raises

    beaneater-1.0.0/lib/beaneater.rb:24:in `initialize': wrong number of arguments (0 for 1) (ArgumentError)

But according to the documentation, it should default to the configuration or then environment variable.

**Comment by tjchambers** [comment]
It appears from the source that the address argument is NOT optional (ie. not (address = nil)), but rather passing 

```
client = Beaneater.new(nil)
```

invokes the ENVIRONMENT variable connection lookup. 

I would expect this is an oversight.

**Comment by nesquena** [comment]
This should be fixed in next release.

**Comment by shashikantgautam** [comment]
To setup advanced options for beaneater, you can pass configuration options using:

Beaneater.configure do |config|
   config.default_put_delay   = 0
   config.default_put_pri     = 65536
   config.default_put_ttr     = 120
  config.beanstalkd_url      = 'localhost:11300'
end

To interact with a beanstalk queue, first establish a connection by providing an address:

@beanstalk = Beaneater.new('10.0.1.5:11300')
# Or if ENV['BEANSTALKD_URL'] == '127.0.0.1:11300'
@beanstalk = Beaneater.new
@beanstalk.connection      # => localhost:11300
